import jsPDF from "jspdf";
import { SolarCalculation, formatCurrency, formatNumber, MONTH_NAMES, systemPackages } from "./solarData";
import { calculateROIProjection } from "./roiProjections";

export type ReportLanguage = "en" | "ar";

// Bilingual labels
const labels = {
  en: {
    title: "SOLAR FEASIBILITY REPORT",
    subtitle: "Powered by SolarMatch — Egypt's Solar Calculator",
    executiveSummary: "EXECUTIVE SUMMARY",
    suitable: "SUITABLE FOR SOLAR",
    conditional: "CONDITIONALLY SUITABLE",
    notRecommended: "NOT RECOMMENDED",
    justificationSuitable: (payback: string, savings: string) =>
      `System pays back in ${payback} years with ${savings} annual savings.`,
    justificationConditional: (coverage: string) =>
      `Partial coverage (${coverage}%) — a smaller system may still be worthwhile.`,
    justificationNot: "Insufficient return based on current roof area and consumption levels.",
    systemSize: "System Size",
    annualProduction: "Annual Production",
    yearlySavings: "Yearly Savings",
    payback: "Payback",
    location: "LOCATION",
    irradiance: "Irradiance",
    keyMetrics: "KEY PERFORMANCE METRICS",
    installedCapacity: "Installed Capacity",
    yearlyProduction: "Yearly Production",
    annualSavings: "Annual Savings",
    totalSystemCost: "Total System Cost",
    perKw: "/kW",
    perMonth: "/month",
    max: "Max",
    coverageAnalysis: "ENERGY COVERAGE ANALYSIS",
    coverageRatio: "Coverage Ratio",
    fullCoverage: "Full coverage with surplus",
    goodCoverage: "Good coverage",
    partialCoverage: "Partial coverage",
    environmentalImpact: "ENVIRONMENTAL IMPACT",
    co2Reduction: "CO₂ Reduction",
    tonsYear: "tons/year",
    treesEquivalent: (n: number) => `Equivalent to planting ${n} trees annually`,
    buildingModeAnalysis: "BUILDING MODE ANALYSIS",
    totalUnits: "Total Units",
    avgConsumption: "Avg. Consumption/Unit",
    totalConsumption: "Total Consumption",
    unitsCovered: "Units Covered",
    kwhMonth: "kWh/month",
    systemConfig: "SYSTEM CONFIGURATION",
    panelPackage: "Panel Package",
    efficiency: "Efficiency",
    areaPerKw: "Area/kW",
    costPerKw: "Cost/kW",
    buildingType: "Building Type",
    usableRoof: "Usable Roof",
    packageComparison: "PACKAGE OPTIONS COMPARISON",
    package: "Package",
    kw: "kW",
    totalCost: "Total Cost",
    savingsYear: "Savings/Year",
    paybackYrs: "Payback",
    yrs: "yrs",
    monthlyProduction: "MONTHLY ENERGY PRODUCTION",
    financialProjection: "25-YEAR FINANCIAL PROJECTION",
    breakEvenYear: "Break-Even Year",
    year: "Year",
    totalSavings25: "Total 25-Year Savings",
    netValue: "Net Value",
    totalROI: "Total ROI",
    recommendedSystem: "RECOMMENDED SYSTEM TYPE",
    warnings: "IMPORTANT NOTES",
    generatedBy: "Generated by SolarMatch — Egypt's Solar Calculator",
    page: "Page",
    of: "of",
    disclaimer: "This report is for preliminary assessment only. Actual results may vary based on site conditions, equipment selection, and installation quality. Consult a certified solar installer for detailed engineering assessment.",
  },
  ar: {
    title: "تقرير جدوى الطاقة الشمسية",
    subtitle: "SolarMatch — حاسبة الطاقة الشمسية في مصر",
    executiveSummary: "الملخص التنفيذي",
    suitable: "مناسب للطاقة الشمسية",
    conditional: "مناسب بشروط",
    notRecommended: "غير موصى به",
    justificationSuitable: (payback: string, savings: string) =>
      `${savings} :فترة استرداد ${payback} سنة مع توفير سنوي`,
    justificationConditional: (coverage: string) =>
      `(%${coverage}) :تغطية جزئية — نظام أصغر قد يكون مجدياً`,
    justificationNot: "عائد غير كافٍ بناءً على مساحة السطح ومستوى الاستهلاك الحالي.",
    systemSize: "حجم النظام",
    annualProduction: "الإنتاج السنوي",
    yearlySavings: "التوفير السنوي",
    payback: "فترة الاسترداد",
    location: "الموقع",
    irradiance: "الإشعاع الشمسي",
    keyMetrics: "مؤشرات الأداء الرئيسية",
    installedCapacity: "السعة المركبة",
    yearlyProduction: "الإنتاج السنوي",
    annualSavings: "التوفير السنوي",
    totalSystemCost: "تكلفة النظام الإجمالية",
    perKw: "/ك.و",
    perMonth: "/شهر",
    max: "الحد الأقصى",
    coverageAnalysis: "تحليل تغطية الطاقة",
    coverageRatio: "نسبة التغطية",
    fullCoverage: "تغطية كاملة مع فائض",
    goodCoverage: "تغطية جيدة",
    partialCoverage: "تغطية جزئية",
    environmentalImpact: "الأثر البيئي",
    co2Reduction: "CO₂ خفض",
    tonsYear: "طن/سنة",
    treesEquivalent: (n: number) => `ما يعادل زراعة ${n} شجرة سنوياً`,
    buildingModeAnalysis: "تحليل وضع المبنى",
    totalUnits: "إجمالي الوحدات",
    avgConsumption: "متوسط الاستهلاك/وحدة",
    totalConsumption: "إجمالي الاستهلاك",
    unitsCovered: "الوحدات المغطاة",
    kwhMonth: "ك.و.س/شهر",
    systemConfig: "إعدادات النظام",
    panelPackage: "باقة الألواح",
    efficiency: "الكفاءة",
    areaPerKw: "المساحة/ك.و",
    costPerKw: "التكلفة/ك.و",
    buildingType: "نوع المبنى",
    usableRoof: "السطح القابل للاستخدام",
    packageComparison: "مقارنة خيارات الباقات",
    package: "الباقة",
    kw: "ك.و",
    totalCost: "التكلفة الإجمالية",
    savingsYear: "التوفير/سنة",
    paybackYrs: "الاسترداد",
    yrs: "سنة",
    monthlyProduction: "الإنتاج الشهري للطاقة",
    financialProjection: "التوقعات المالية لـ 25 سنة",
    breakEvenYear: "سنة التعادل",
    year: "السنة",
    totalSavings25: "إجمالي التوفير على 25 سنة",
    netValue: "صافي القيمة",
    totalROI: "إجمالي العائد",
    recommendedSystem: "نوع النظام الموصى به",
    warnings: "ملاحظات مهمة",
    generatedBy: "SolarMatch — حاسبة الطاقة الشمسية في مصر",
    page: "صفحة",
    of: "من",
    disclaimer: "هذا التقرير للتقييم المبدئي فقط. قد تختلف النتائج الفعلية بناءً على ظروف الموقع واختيار المعدات وجودة التركيب. استشر مركب طاقة شمسية معتمد للتقييم الهندسي المفصل.",
  },
};

export async function generateSolarReport(
  results: SolarCalculation,
  locationName?: string,
  language: ReportLanguage = "en"
): Promise<void> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  let yPos = margin;
  const L = labels[language];

  // Helper functions
  const addText = (
    text: string,
    x: number,
    y: number,
    options?: {
      fontSize?: number;
      fontStyle?: "normal" | "bold";
      color?: [number, number, number];
      align?: "left" | "center" | "right";
    }
  ) => {
    const { fontSize = 10, fontStyle = "normal", color = [0, 0, 0], align = "left" } = options || {};
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", fontStyle);
    doc.setTextColor(...color);
    doc.text(text, x, y, { align });
    return fontSize * 0.4 + 2;
  };

  const addLine = (y: number, color: [number, number, number] = [220, 220, 220]) => {
    doc.setDrawColor(...color);
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageWidth - margin, y);
  };

  const checkNewPage = (neededSpace: number) => {
    if (yPos + neededSpace > pageHeight - 28) {
      doc.addPage();
      yPos = margin + 5;
      return true;
    }
    return false;
  };

  const drawProgressBar = (
    x: number,
    y: number,
    width: number,
    height: number,
    progress: number,
    color: [number, number, number]
  ) => {
    doc.setFillColor(235, 235, 235);
    doc.roundedRect(x, y, width, height, height / 2, height / 2, "F");
    doc.setFillColor(...color);
    doc.roundedRect(x, y, width * Math.min(progress, 1), height, height / 2, height / 2, "F");
  };

  // ============================================
  // HEADER
  // ============================================
  // Main teal bar
  doc.setFillColor(13, 148, 136);
  doc.rect(0, 0, pageWidth, 42, "F");
  // Accent bottom strip
  doc.setFillColor(15, 118, 110);
  doc.rect(0, 38, pageWidth, 4, "F");

  addText(L.title, pageWidth / 2, 17, { fontSize: 20, fontStyle: "bold", color: [255, 255, 255], align: "center" });
  addText(L.subtitle, pageWidth / 2, 26, { fontSize: 9, color: [200, 245, 240], align: "center" });

  const dateStr = new Date().toLocaleDateString(language === "ar" ? "ar-EG" : "en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  addText(dateStr, pageWidth / 2, 34, { fontSize: 8, color: [180, 235, 230], align: "center" });

  yPos = 52;

  // ============================================
  // EXECUTIVE SUMMARY
  // ============================================
  const summaryHeight = 52;
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, yPos - 4, pageWidth - margin * 2, summaryHeight, 4, 4, "F");
  doc.setDrawColor(13, 148, 136);
  doc.setLineWidth(0.8);
  doc.roundedRect(margin, yPos - 4, pageWidth - margin * 2, summaryHeight, 4, 4, "S");

  // Section label
  addText(L.executiveSummary, margin + 8, yPos + 4, { fontSize: 10, fontStyle: "bold", color: [13, 148, 136] });

  // Feasibility status
  const isSuitable = results.coverageRatio >= 0.7 && results.paybackYears <= 10;
  const isConditional = results.coverageRatio >= 0.3 && results.paybackYears <= 15;
  const statusText = isSuitable ? L.suitable : isConditional ? L.conditional : L.notRecommended;
  const statusColor: [number, number, number] = isSuitable ? [22, 163, 74] : isConditional ? [217, 119, 6] : [220, 38, 38];

  // Status badge
  const badgeX = margin + 8;
  const badgeY = yPos + 8;
  doc.setFillColor(...statusColor);
  doc.roundedRect(badgeX, badgeY, 3, 10, 1, 1, "F");
  addText(statusText, badgeX + 6, badgeY + 7, { fontSize: 10, fontStyle: "bold", color: statusColor });

  // Justification
  const justification = isSuitable
    ? L.justificationSuitable(formatNumber(results.paybackYears, 1), formatCurrency(results.savingsYear))
    : isConditional
      ? L.justificationConditional(formatNumber(results.coverageRatio * 100, 0))
      : L.justificationNot;
  addText(justification, margin + 14, yPos + 24, { fontSize: 8, color: [100, 100, 100] });

  // Key summary stats
  const summaryItems = [
    { label: L.systemSize, value: `${results.kWInstalled} kW` },
    { label: L.annualProduction, value: `${formatNumber(results.energyYear, 0)} kWh` },
    { label: L.yearlySavings, value: formatCurrency(results.savingsYear) },
    { label: L.payback, value: `${formatNumber(results.paybackYears, 1)} ${L.yrs}` },
  ];

  const itemWidth = (pageWidth - margin * 2 - 16) / 4;
  summaryItems.forEach((item, i) => {
    const xPos = margin + 8 + i * itemWidth;
    addText(item.label, xPos, yPos + 34, { fontSize: 7, color: [120, 120, 120] });
    addText(item.value, xPos, yPos + 42, { fontSize: 11, fontStyle: "bold", color: [30, 30, 30] });
  });

  yPos += summaryHeight + 8;

  // ============================================
  // LOCATION
  // ============================================
  if (locationName || results.climateData?.location) {
    doc.setFillColor(255, 251, 235);
    doc.roundedRect(margin, yPos - 3, pageWidth - margin * 2, 20, 3, 3, "F");

    addText(L.location, margin + 6, yPos + 4, { fontSize: 9, fontStyle: "bold", color: [180, 83, 9] });

    let locText = locationName || "";
    if (results.climateData?.location) {
      if (locText) locText += "  |  ";
      locText += `${results.climateData.location.lat.toFixed(4)}N, ${results.climateData.location.lng.toFixed(4)}E`;
    }
    if (results.climateData?.annualAvgIrradiance) {
      locText += `  |  ${L.irradiance}: ${formatNumber(results.climateData.annualAvgIrradiance, 2)} kWh/m²/day`;
    }
    addText(locText, margin + 6, yPos + 13, { fontSize: 8, color: [120, 90, 50] });
    yPos += 26;
  }

  // ============================================
  // KEY METRICS
  // ============================================
  addText(L.keyMetrics, margin, yPos, { fontSize: 11, fontStyle: "bold", color: [13, 148, 136] });
  yPos += 10;

  const metrics = [
    { label: L.installedCapacity, value: `${results.kWInstalled} kW`, sub: `${L.max}: ${formatNumber(results.kWMax, 1)} kW`, color: [13, 148, 136] as [number, number, number] },
    { label: L.yearlyProduction, value: `${formatNumber(results.energyYear, 0)} kWh`, sub: `${formatNumber(results.energyMonth, 0)} kWh${L.perMonth}`, color: [217, 119, 6] as [number, number, number] },
    { label: L.annualSavings, value: formatCurrency(results.savingsYear), sub: `${formatCurrency(results.savingsMonth)}${L.perMonth}`, color: [22, 163, 74] as [number, number, number] },
    { label: L.totalSystemCost, value: formatCurrency(results.totalCost), sub: `${formatCurrency(results.totalCost / results.kWInstalled)}${L.perKw}`, color: [79, 70, 229] as [number, number, number] },
  ];

  const metricWidth = (pageWidth - margin * 2 - 8) / 2;
  metrics.forEach((metric, i) => {
    const row = Math.floor(i / 2);
    const col = i % 2;
    const xPos = margin + col * (metricWidth + 8);
    const yBase = yPos + row * 24;

    // Color accent bar
    doc.setFillColor(...metric.color);
    doc.roundedRect(xPos, yBase - 2, 3, 18, 1, 1, "F");

    // Card background
    doc.setFillColor(250, 250, 252);
    doc.roundedRect(xPos + 5, yBase - 2, metricWidth - 8, 18, 3, 3, "F");

    addText(metric.label, xPos + 9, yBase + 4, { fontSize: 7, color: [120, 120, 120] });
    addText(metric.value, xPos + 9, yBase + 11, { fontSize: 11, fontStyle: "bold" });
    addText(metric.sub, xPos + metricWidth - 38, yBase + 11, { fontSize: 7, color: [120, 120, 120] });
  });

  yPos += 54;

  // ============================================
  // COVERAGE RATIO
  // ============================================
  addText(L.coverageAnalysis, margin, yPos, { fontSize: 11, fontStyle: "bold", color: [13, 148, 136] });
  yPos += 10;

  addText(`${L.coverageRatio}: ${formatNumber(results.coverageRatio * 100, 0)}%`, margin, yPos + 3, { fontSize: 10, fontStyle: "bold" });
  drawProgressBar(margin + 60, yPos, 70, 7, results.coverageRatio, [13, 148, 136]);

  const coverageText = results.coverageRatio >= 1 ? L.fullCoverage : results.coverageRatio >= 0.7 ? L.goodCoverage : L.partialCoverage;
  addText(coverageText, margin + 135, yPos + 3, { fontSize: 8, color: results.coverageRatio >= 1 ? [22, 163, 74] : [120, 120, 120] });

  yPos += 14;

  // ============================================
  // ENVIRONMENTAL IMPACT
  // ============================================
  doc.setFillColor(236, 253, 245);
  doc.roundedRect(margin, yPos - 2, pageWidth - margin * 2, 18, 3, 3, "F");

  addText(L.environmentalImpact, margin + 6, yPos + 5, { fontSize: 9, fontStyle: "bold", color: [22, 163, 74] });
  addText(`${L.co2Reduction}: ${formatNumber(results.co2Saved, 1)} ${L.tonsYear}`, margin + 6, yPos + 12, { fontSize: 8, color: [22, 101, 52] });

  const treesEquivalent = Math.round(results.co2Saved * 45);
  addText(L.treesEquivalent(treesEquivalent), margin + 80, yPos + 12, { fontSize: 8, color: [22, 101, 52] });

  yPos += 24;
  addLine(yPos);
  yPos += 8;

  // ============================================
  // BUILDING MODE ANALYSIS
  // ============================================
  if (results.buildingMode) {
    checkNewPage(50);
    addText(L.buildingModeAnalysis, margin, yPos, { fontSize: 11, fontStyle: "bold", color: [13, 148, 136] });
    yPos += 10;

    const buildingData = [
      [L.totalUnits, `${results.numberOfUnits}`],
      [L.avgConsumption, `${results.avgUnitConsumption} ${L.kwhMonth}`],
      [L.totalConsumption, `${formatNumber(results.effectiveMonthlyConsumption, 0)} ${L.kwhMonth}`],
      [L.unitsCovered, `${formatNumber(results.unitsCovered, 1)}`],
    ];

    const bWidth = (pageWidth - margin * 2 - 8) / 2;
    buildingData.forEach((row, i) => {
      const col = i % 2;
      const rowNum = Math.floor(i / 2);
      const xPos = margin + col * (bWidth + 8);
      const yBase = yPos + rowNum * 12;
      addText(row[0] + ":", xPos, yBase, { fontSize: 8, color: [100, 100, 100] });
      addText(row[1], xPos + 52, yBase, { fontSize: 9, fontStyle: "bold" });
    });

    yPos += 30;
    addLine(yPos);
    yPos += 8;
  }

  // ============================================
  // SYSTEM CONFIGURATION
  // ============================================
  checkNewPage(50);
  addText(L.systemConfig, margin, yPos, { fontSize: 11, fontStyle: "bold", color: [13, 148, 136] });
  yPos += 10;

  const selectedPkg = systemPackages[results.selectedPackage];

  doc.setFillColor(250, 250, 252);
  doc.roundedRect(margin, yPos - 3, pageWidth - margin * 2, 32, 3, 3, "F");

  const configItems = [
    { label: L.panelPackage, value: selectedPkg?.name || results.selectedPackage },
    { label: L.efficiency, value: selectedPkg?.efficiency || "N/A" },
    { label: L.areaPerKw, value: `${selectedPkg?.areaPerKW || "N/A"} m²` },
    { label: L.costPerKw, value: `${selectedPkg?.costPerKW?.toLocaleString() || "N/A"} EGP` },
  ];

  const confWidth = (pageWidth - margin * 2) / 4;
  configItems.forEach((item, i) => {
    const xPos = margin + 4 + i * confWidth;
    addText(item.label, xPos, yPos + 5, { fontSize: 7, color: [120, 120, 120] });
    addText(item.value, xPos, yPos + 13, { fontSize: 9, fontStyle: "bold" });
  });

  addText(`${L.buildingType}:`, margin + 4, yPos + 24, { fontSize: 7, color: [120, 120, 120] });
  addText(results.buildingType.charAt(0).toUpperCase() + results.buildingType.slice(1), margin + 40, yPos + 24, { fontSize: 9, fontStyle: "bold" });

  addText(`${L.usableRoof}:`, margin + 95, yPos + 24, { fontSize: 7, color: [120, 120, 120] });
  addText(`${formatNumber(results.usableArea, 0)} m²`, margin + 128, yPos + 24, { fontSize: 9, fontStyle: "bold" });

  yPos += 40;

  // ============================================
  // PACKAGE OPTIONS COMPARISON
  // ============================================
  if (results.packageOptions && results.packageOptions.length > 0) {
    checkNewPage(80);
    addText(L.packageComparison, margin, yPos, { fontSize: 11, fontStyle: "bold", color: [13, 148, 136] });
    yPos += 10;

    const colWidths = [42, 28, 45, 40, 28];
    const headers = [L.package, L.kw, L.totalCost, L.savingsYear, L.paybackYrs];

    doc.setFillColor(13, 148, 136);
    doc.roundedRect(margin, yPos - 3, pageWidth - margin * 2, 11, 2, 2, "F");

    let xPos = margin + 4;
    headers.forEach((header, i) => {
      addText(header, xPos, yPos + 4, { fontSize: 7, fontStyle: "bold", color: [255, 255, 255] });
      xPos += colWidths[i];
    });
    yPos += 12;

    results.packageOptions.forEach((option, idx) => {
      const isSelected = option.packageKey === results.selectedPackage;

      if (isSelected) {
        doc.setFillColor(236, 253, 245);
        doc.rect(margin, yPos - 3, pageWidth - margin * 2, 11, "F");
      } else if (idx % 2 === 0) {
        doc.setFillColor(250, 250, 252);
        doc.rect(margin, yPos - 3, pageWidth - margin * 2, 11, "F");
      }

      xPos = margin + 4;
      addText(option.package.name + (isSelected ? " ✓" : ""), xPos, yPos + 4, {
        fontSize: 8,
        fontStyle: isSelected ? "bold" : "normal",
        color: isSelected ? [22, 163, 74] : [0, 0, 0],
      });
      xPos += colWidths[0];
      addText(`${option.kWInstalled}`, xPos, yPos + 4, { fontSize: 8 });
      xPos += colWidths[1];
      addText(formatCurrency(option.totalCost), xPos, yPos + 4, { fontSize: 8 });
      xPos += colWidths[2];
      addText(formatCurrency(option.savingsYear), xPos, yPos + 4, { fontSize: 8 });
      xPos += colWidths[3];
      addText(`${formatNumber(option.paybackYears, 1)} ${L.yrs}`, xPos, yPos + 4, { fontSize: 8 });

      yPos += 11;
    });

    yPos += 6;
  }

  // ============================================
  // MONTHLY PRODUCTION CHART
  // ============================================
  checkNewPage(75);
  addText(L.monthlyProduction, margin, yPos, { fontSize: 11, fontStyle: "bold", color: [13, 148, 136] });
  yPos += 10;

  const maxProduction = Math.max(...results.monthlyProduction);
  const barWidth = (pageWidth - margin * 2 - 24) / 12;
  const barMaxHeight = 32;

  results.monthlyProduction.forEach((production, i) => {
    const barHeight = (production / maxProduction) * barMaxHeight;
    const xPos = margin + i * (barWidth + 2);

    // Bar with rounded top
    doc.setFillColor(13, 148, 136);
    doc.roundedRect(xPos, yPos + (barMaxHeight - barHeight), barWidth, barHeight, 1, 1, "F");

    // Month label
    addText(MONTH_NAMES[i].substring(0, 3), xPos + 1, yPos + barMaxHeight + 7, { fontSize: 5.5, color: [120, 120, 120] });

    // Value on top
    addText(formatNumber(production, 0), xPos, yPos + (barMaxHeight - barHeight) - 2, { fontSize: 5, color: [120, 120, 120] });
  });

  yPos += barMaxHeight + 16;

  // ============================================
  // 25-YEAR ROI PROJECTION
  // ============================================
  const impliedElectricityPrice = results.savingsYear / results.energyYear;
  const roiAnalysis = calculateROIProjection(results.totalCost, results.energyYear, impliedElectricityPrice, {});

  if (roiAnalysis.yearlyProjections.length > 0) {
    checkNewPage(60);
    addText(L.financialProjection, margin, yPos, { fontSize: 11, fontStyle: "bold", color: [13, 148, 136] });
    yPos += 10;

    const breakEvenYear = roiAnalysis.yearlyProjections.findIndex((p) => p.netPosition >= 0) + 1;
    const finalValue = roiAnalysis.yearlyProjections[roiAnalysis.yearlyProjections.length - 1];

    doc.setFillColor(250, 250, 252);
    doc.roundedRect(margin, yPos - 3, pageWidth - margin * 2, 22, 3, 3, "F");

    addText(`${L.breakEvenYear}:`, margin + 6, yPos + 5, { fontSize: 8, color: [120, 120, 120] });
    addText(`${L.year} ${breakEvenYear}`, margin + 42, yPos + 5, { fontSize: 10, fontStyle: "bold", color: [22, 163, 74] });

    addText(`${L.totalSavings25}:`, margin + 70, yPos + 5, { fontSize: 8, color: [120, 120, 120] });
    addText(formatCurrency(finalValue.cumulativeSavings), margin + 122, yPos + 5, { fontSize: 10, fontStyle: "bold", color: [13, 148, 136] });

    addText(`${L.netValue}:`, margin + 6, yPos + 15, { fontSize: 8, color: [120, 120, 120] });
    addText(formatCurrency(finalValue.netPosition), margin + 32, yPos + 15, { fontSize: 10, fontStyle: "bold" });

    const totalROI = (finalValue.netPosition / results.totalCost) * 100;
    addText(`${L.totalROI}:`, margin + 70, yPos + 15, { fontSize: 8, color: [120, 120, 120] });
    addText(`${formatNumber(totalROI, 0)}%`, margin + 96, yPos + 15, {
      fontSize: 10,
      fontStyle: "bold",
      color: totalROI > 0 ? [22, 163, 74] : [220, 38, 38],
    });

    yPos += 30;
  }

  // ============================================
  // CONNECTION RECOMMENDATION
  // ============================================
  if (results.connectionRecommendation) {
    checkNewPage(35);

    const recColor =
      results.connectionRecommendation.icon === "offgrid"
        ? ([22, 163, 74] as [number, number, number])
        : results.connectionRecommendation.icon === "hybrid"
          ? ([217, 119, 6] as [number, number, number])
          : ([13, 148, 136] as [number, number, number]);

    doc.setFillColor(...recColor);
    doc.roundedRect(margin, yPos - 2, 3, 22, 1, 1, "F");

    doc.setFillColor(250, 250, 252);
    doc.roundedRect(margin + 5, yPos - 2, pageWidth - margin * 2 - 5, 22, 3, 3, "F");

    addText(L.recommendedSystem, margin + 9, yPos + 5, { fontSize: 8, fontStyle: "bold", color: recColor });
    addText(results.connectionRecommendation.systemType, margin + 72, yPos + 5, { fontSize: 10, fontStyle: "bold" });

    const splitReason = doc.splitTextToSize(results.connectionRecommendation.reason, pageWidth - margin * 2 - 18);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    doc.text(splitReason, margin + 9, yPos + 14);

    yPos += 28;
  }

  // ============================================
  // WARNINGS
  // ============================================
  if (results.warnings.length > 0) {
    checkNewPage(35);

    doc.setFillColor(254, 243, 199);
    doc.roundedRect(margin, yPos - 2, pageWidth - margin * 2, 8 + results.warnings.length * 7, 3, 3, "F");

    addText(L.warnings, margin + 6, yPos + 4, { fontSize: 8, fontStyle: "bold", color: [180, 83, 9] });
    yPos += 10;

    results.warnings.forEach((warning) => {
      const splitWarning = doc.splitTextToSize("• " + warning, pageWidth - margin * 2 - 14);
      doc.setFontSize(7);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(140, 100, 40);
      doc.text(splitWarning, margin + 8, yPos);
      yPos += splitWarning.length * 4.5 + 2;
    });

    yPos += 4;
  }

  // ============================================
  // DISCLAIMER
  // ============================================
  checkNewPage(25);
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(margin, yPos - 2, pageWidth - margin * 2, 18, 3, 3, "F");
  const disclaimerLines = doc.splitTextToSize(L.disclaimer, pageWidth - margin * 2 - 12);
  doc.setFontSize(6.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(130, 130, 130);
  doc.text(disclaimerLines, margin + 6, yPos + 5);
  yPos += 22;

  // ============================================
  // FOOTER
  // ============================================
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    doc.setFillColor(248, 250, 252);
    doc.rect(0, pageHeight - 16, pageWidth, 16, "F");

    doc.setDrawColor(13, 148, 136);
    doc.setLineWidth(0.4);
    doc.line(margin, pageHeight - 16, pageWidth - margin, pageHeight - 16);

    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(130, 130, 130);
    doc.text(L.generatedBy, margin, pageHeight - 7);
    doc.text("solarmatch.lovable.app", margin, pageHeight - 3);

    doc.setTextColor(13, 148, 136);
    doc.text(`${L.page} ${i} ${L.of} ${totalPages}`, pageWidth - margin - 22, pageHeight - 5);
  }

  // Save
  const langSuffix = language === "ar" ? "AR" : "EN";
  const filename = `SolarMatch_Report_${langSuffix}_${locationName?.replace(/[^a-zA-Z0-9]/g, "_") || "Report"}_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
}
