project_id = "hgskuophhidgbuluxiel"

[functions.solar-advisor]
verify_jwt = false

[functions.building-footprints]
verify_jwt = false

[functions.solar-engine]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.google-solar]
verify_jwt = false

[functions.detect-rooftop]
verify_jwt = false